default: &default
  adapter: postgresql
  encoding: unicode

development:
  <<: *default
  database: zomeki_development
  username: zomeki
  password: zomekipass

test:
  <<: *default
  database: zomeki_test
  username: zomeki
  password: zomekipass

production:
  <<: *default
  database: zomeki_production
  username: zomeki
  password: zomekipass
